### PR TITLE
Fixed update status endpoint to include prefix & version

### LINKED ISSUE #282: Update status endpoint should include prefix & version

### PR DESCRIPTION
**Pull request by Emulebest**
resolves #282

### CODE REVIEW

File: papiea-backend-utils/src/logging.ts [hunk 1]
```diff
@@ -46,7 +46,6 @@ export class LoggerFactory {
     readonly options: LoggerOptions
 
     private static readonly INSPECT_OPTIONS = {
-        colors: true, depth: 3, maxStringLength: 120,
```
Comment (shlomi-nx) [inline papiea-backend-utils/src/logging.ts:49]: Already seen this in another PR.. Why are we removing colors?

Comment (Emulebest) [reply papiea-backend-utils/src/logging.ts:49]: It's the 2nd PR where I keep forgetting to address this change. The coloring seems to generate exceptions on my machine (I suspect it's because some optional dep being ommited), which isn't a big problem by itself. The problem is that coloring exceptions prevent all other logs from working. I think I'll file a ticket to introduce safer coloring and fix bugs on some machines
