### PR TITLE
Changed logger to be pretty printed & fixed a bug and added test

### LINKED ISSUE #294: Pretty print logs in console

### PR DESCRIPTION
**Pull request by Emulebest**
resolves #294 
New logs in console look like the following:
```
{  
   "0":{  
      "two":"errors"
   },
   "1":{  
      "three":"errors"
   },
   "2":{  
      "Time":"2019-08-21T15:00:42.118Z"
   },
   "level":"error",
   "message":{  
      "one":"error"
   }
}
```

### CODE REVIEW

File: papiea-engine/src/logger.ts [hunk 1]
```diff
@@ -49,16 +42,22 @@ export class WinstonLogger implements Logger {
         if (!this.isValidLevel(logLevel)) {
```
Comment (nkntnx) [inline papiea-engine/src/logger.ts]: Should we lose the log just because the log level is incorrect ? I suggest we log that we found an invalid log level, and then use error as the default logging here. That way the flow won't break in case of invalid log level.

File: papiea-engine/src/logger.ts [hunk 2]
```diff
@@ -49,16 +42,22 @@ export class WinstonLogger implements Logger {
...
             transports: [
-                new winston.transports.File({ filename: logFile ?
-                    resolve(__dirname, `./logs/${logFile}`) :
-                    resolve(__dirname, `./logs/papiea_${logLevel}.log`) }),
-                new winston.transports.Console()
+                new winston.transports.File({
+                    filename: logFile ?
+                        resolve(__dirname, `./logs/${ logFile }`) :
+                        resolve(__dirname, `./logs/papiea_${ logLevel }.log`),
+                    format: winston.format.json()
```
Comment (nkntnx) [inline papiea-engine/src/logger.ts]: Why not use the winstonFormat here too ?

**Comment by nkntnx** [comment]
Can you also add a sample log file output to the review comments somewhere to see the new output ?

File: papiea-engine/src/logger.ts (hunk 1 above)
Comment (Emulebest) [reply papiea-engine/src/logger.ts]: I believe that we shouldn't confuse error logs with incorrect level logs. This way this might bloat the the error log with unexpected logs

File: papiea-engine/src/logger.ts (hunk 2 above)
Comment (Emulebest) [reply papiea-engine/src/logger.ts]: Pretty print insert a lot of indents which negatively affects log file size

File: papiea-engine/src/logger.ts (hunk 1 above)
Comment (shlomi-nx) [reply papiea-engine/src/logger.ts]: @Emulebest I agree with @nkntnx here. Logging something is better than silently ignore problems. I rather see bloated logs that point me to the problem which I could then fix, than this opaque `Unsupported logging level ` error which tells me that something somewhere gone wrong. 

If we get an unsupported logging level, I would implicitly make it as a `warning` level, and write that `Unsupported logging level` was used, along with the original log message and potentially its location in the code.

File: papiea-engine/src/logger.ts (hunk 2 above)
Comment (shlomi-nx) [reply papiea-engine/src/logger.ts]: We should not pre-optimize for file size.

File: papiea-engine/src/logger.ts (hunk 1 above)
Comment (nkntnx) [reply papiea-engine/src/logger.ts]: Fixed this.

File: papiea-engine/src/utils/utils.ts [hunk 3]
```diff
@@ -70,4 +70,12 @@ export function isEmpty(obj: any) {
             return false;
     }
     return true;
+}
+
+export function safeJSONParse(chunk: string) {
+    try {
+        return JSON.parse(chunk)
+    } catch (e) {
+        return undefined
```
Comment (shlomi-nx) [inline papiea-engine/src/utils/utils.ts]: Should we just silently ignore errors? Can't this hide real problems?

**Comment by shlomi-nx** [comment]
@Emulebest @nkntnx If this is done, please merge
