### PR TITLE
Fix provider error message propagation

### LINKED ISSUE #316: More descriptive error logs from typescript sdk
Example:
```
{
  "error": {
    "code": 500,
    "errors": [
      {
        "message": "Could not create xi-cluster on AWS: Cannot create new key: Request failed with status code 400",
        "stacktrace": "Error: Could not create xi-cluster on AWS: Cannot create new key: Request failed with status code 400\n    at Function.fromError (/home/node/xi-clusters-provider/node_modules/papiea-sdk/build/provider_sdk/typescript_sdk_exceptions.js:17:16)\n    at server_manager.register_handler (/home/node/xi-clusters-provider/node_modules/papiea-sdk/build/provider_sdk/typescript_sdk.js:377:75)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
      }
    ],
    "message": "Procedure invocation failed."
  }
}
```
The papiea itself provides error description:
VirtualBox_Ubuntu_21_10_2019_17_45_17

When procedure invocation fails due to error from papiea, the reason of "root" error should be propagated, e.g. instead of just "Request failed with status code 400" there should be a message "provider_prefix may not be specified in the request body"

### PR DESCRIPTION
**Pull request by Emulebest**
resolves #316

### CODE REVIEW

File: papiea-sdk/src/provider_sdk/typescript_sdk.ts [hunk 1]
```diff
@@ -30,8 +30,11 @@ class SecurityApiImpl implements SecurityApi {
             const {data: user_info } = await this.provider.provider_api_axios.get(`${url}/auth/user_info`, {headers: {'Authorization': `Bearer ${this.s2s_key}`}});
             return user_info
         } catch (e) {
-            console.log("error getting user_info", e);
-            throw new Error("Cannot get user info" + e.message)
+            if (e.response.data.error) {
+                throw new Error(`Cannot get user info: Response status: ${e.response.data.error.code}, Errors: ${JSON.stringify(e.response.data.error.errors)}`)
+            } else {
+                throw new Error(`Cannot get user info: ${e.message}`)
+            }
```
Comment (adolgarev) [inline papiea-sdk/src/provider_sdk/typescript_sdk.ts]: * we repeat this snippet 3 times
* there should be a way to programmatically process error message, that is it should be a JSON, not a string
* and what we have on create_aws_cluster procedure side:
```
export async function create_aws_cluster(ctx: IntentfulCtx_Interface, input: any) {
    try {
        ...
    } catch (e) {
        console.error(now(), 'Could not create xi-cluster on AWS', e)
        if (e.response && e.response.data && e.response.data.errors)
            throw { code: 0, message: `Could not create xi-cluster on AWS: ${e.message}, ${JSON.stringify(e.response.data.errors)}` }
        else
            throw { code: 0, message: `Could not create xi-cluster on AWS: ${e.message}` }
    }
}
```
* this covers security api, what about ctx.update_status() and other ctx.... methods?
* what it should be from procedure writer perspective
```
export async function create_aws_cluster(ctx: IntentfulCtx_Interface, input: any) {
    ...call any ctx... methods including security api, do nothing additional to catch and post-process error message, just throw it and client who invoked this procedure will see all details if they are available
}
```
